
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-manager
  labels:
    app: file-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-manager
  template:
    metadata:
      labels:
        app: file-manager
    spec:
      containers:
      - name: file-manager
        image: file-manager:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: file-manager-service
spec:
  selector:
    app: file-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
