
apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-manager-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-manager-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-manager
  labels:
    app: file-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-manager
  template:
    metadata:
      labels:
        app: file-manager
    spec:
      containers:
      - name: file-manager
        image: file-manager:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: file-storage
          mountPath: /usr/share/nginx/html/uploads
      volumes:
      - name: file-storage
        persistentVolumeClaim:
          claimName: file-manager-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: file-manager-service
spec:
  selector:
    app: file-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

